# Generated by Django 4.2.3 on 2023-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('ELECTRONICS', 'ELECTRONICS'), ('FOOD', 'FOOD'), ('HEALTHCARE', 'HEALTHCARE'), ('AUTO', 'AUTO'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
